namespace 'celdocs'

export[...] {
  functiondef['cel:hasfocus'] {
    description = [[Check if a cel has focus.]];

    synopsis = [==[
      acel:hasfocus([inputsource])
    ]==];

    params = {
      param.cel[[self - self]];
      param.inputsource[[inputsource - Defaults to cel.keyboard if nil]];
    };

    returns = {
      param.number[[focusorder - An integer >= 1 if an event generated by the inputsource will be delivered to the cel.
        nil if the cel does not have focus. The value of focusorder indicates the order in which a cel will
        receive events. 1 means the cel will receive events first]];
      param.inputsource[[inputsource - The inputsource the cel has focus on.]]
    };
  };

  notes {
    [[TODO ]];
  };
}
