namespace 'celdocs'

export[...] {
  functiondef['cel:takefocus'] {
    description = [[Gives a cel focus, setting it first in the focus order.  This has no effect for the mouse.]];

    synopsis = [==[
      acel:takefocus([inputsource])
    ]==];

    params = {
      param.cel[[self - self]];
      param.inputsource[[inputsource - Defaults to cel.keyboard if nil]];
    };

    returns = {
      param.number[[focusorder - An integer >= 1 if an event generated by the inputsource will be delivered to the cel.
                    nil if the cel does not have focus.
                    the value of focusorder indicates the order in which a cel will receive events.
                    1 means the cel will receive events first]];
      param.inputsource[[inputsource - The inputsource the cel has focus on.]]
    };
  };

  notes {
    [[takefocus has no effect if the cel already has focus and none of its links has focus of the inputsource.]];
    [[The onfocus(inputsource, false) event is sent to all cels that lose focus followed by onfocus(inputsource, true)
      for each cel that gain focus.  This means that there is opportunity for another cel to take focus before
      takefoucs returns.]];
    [[The focus of the mouse is controlled by moving the mouse pointer, takefocus will have no effect on the mouse 
      focus.]]
  };
}
